name: 自助构建
description: 使用此模板进行自助打包构建
title: "[self-build] "
labels: 
  - self-build
body:
  - type: markdown
    attributes:
      value: >
        请填写以下构建参数，保存即触发构建。

        以下为 Deepin V23 环境的 deb 包参数模板，若 deb 包基于 Deepin V20 或 UOS 环境，请参考底部的模板。

        **参数说明：**
        - **Package**: 必填，deb 包名称。
        - **Base**: 可选，基础构建环境，默认为 `org.deepin.base/23.1.0`。
        - **APT-Sources**: 可选，使用的 APT 软件源，支持多个源，请使用 `[trusted=yes]` 忽略签名。
        - **Description**: 可选，软件包的描述信息，支持多行内容，行首有一个普通空格。

  - type: textarea
    id: build-parameters
    attributes:
      label: 构建参数
      description: 请在下方填写所有构建参数
      placeholder: |
        ```package
        Package: <deb包名>
        Base: org.deepin.base/23.1.0
        APT-Sources:
         deb [trusted=yes] https://mirrors.tuna.tsinghua.edu.cn/deepin/beige beige main commercial community
         deb [trusted=yes] https://com-store-packages.uniontech.com/appstorev23 beige appstore
        Description: 简单描述该包的用途
        ```

  - type: markdown
    attributes:
      value: >
        ### 示例模板
        [GIMP](https://github.com/System233/linglong-killer-self-service/blob/main/tests/gimp.md)


        ### Deepin V20/UOS 环境模板
        ```package
        Package: <deb包名>
        Base: org.deepin.foundation/20.0.0
        APT-Sources:
         deb [trusted=yes] https://mirrors.tuna.tsinghua.edu.cn/deepin/apricot apricot main contrib non-free
         deb [trusted=yes] https://pro-store-packages.uniontech.com/appstore eagle-pro appstore
        ```

        请根据实际情况填写正确的参数。
