#!/bin/bash

ROOT_DIR=$(dirname $(readlink -f "$BASH_SOURCE"))
BIN_DIR=$PREFIX/bin
ENTRYPOINT_NAME=entrypoint.sh
LL_SOURCES_DIR=/project/linglong/sources
LL_SOURCES_LIST_DIR=/project/sources.d
LL_KILLER_EXEC=$ROOT_DIR/../resources/ll-killer
LL_ENTRYPOINT=$ROOT_DIR/$ENTRYPOINT_NAME
LL_ENTRYPOINT_BIN=$BIN_DIR/$ENTRYPOINT_NAME
LL_ENTRYPOINT_ROOT=$PREFIX/$ENTRYPOINT_NAME
LL_KILLER_SH=$ROOT_DIR/ll-killer

RES_DIR=$ROOT_DIR/../resources
SCRIPT_DIR=$ROOT_DIR
LL_KILLER_EXEC=$RES_DIR/ll-killer
DPKG_EXEC=$SCRIPT_DIR/dpkg
APT_CONF=$RES_DIR/apt.conf
